### ISSUE TITLE
React-RTE and Meteor.js

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [sstur/react-rte#92] opened 2016-08-20 13:43 UTC
Getting an odd message when using with Meteor but everything seems to be working right. Not sure what the !!. is suppose to be doing.

Unable to resolve some modules:

"!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./Button.css"
in /home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)

"!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./ButtonWrap.css"
in /home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)

"!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./IconButton.css"
in /home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)

"!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./ButtonGroup.css"
in /home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)

"!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./InputPopover.css"
in /home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)

"!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./Dropdown.css"
in /home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)

"!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./EditorToolbar.css"
in /home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)
  "!!./../node_modules/raw-loader/index.js!./Draft.global.css" in
/home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)

"!!./../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./RichTextEditor.css"
in /home/michael/www/ampn/node_modules/react-rte/dist/react-rte.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save !!.

**Comment by sstur** [comment] 2016-08-21 08:00
Hi @MichaelLeeHobbs. This is essentially a duplicate of several other open issues. The problem is related to CSS Modules and there is one proposed solution, in the form of a pull request which may or may not fix it. I will close this one as a duplicate issue but follow along on #55.

**Closed by sstur** 2016-08-21 08:00 UTC
