### ISSUE TITLE
No more icons in the toolbar (v0.13)

### ISSUE THREAD

**Issue by durdenx** [sstur/react-rte#222] opened 2017-07-26 18:14 UTC
Hello, 

Since the new update, 0.13, icons are no more displayed in the toolbar. I don't know how to fix that, i don't use webpack...

![image](https://user-images.githubusercontent.com/6159227/28636630-0f9be6f6-723f-11e7-8e6f-b069c553ccf4.png)

Any ideas?

Thanks.

**Comment by sstur** [comment] 2017-07-27 00:06
Hi @durdenx. I've identified [the cause](https://github.com/sstur/react-rte/commit/820bc12ccb4023a6e471f96de368e16f164902d5) for this issue and we'll release an update soon.

**Comment by sstur** [comment] 2017-07-27 02:26
This has been fixed in react-rte@0.14.0

**Closed by sstur** 2017-07-27 02:26 UTC
