### ISSUE TITLE
createValueFromString and toString renders text backwards

### ISSUE THREAD

**Issue by cfkenandy** [sstur/react-rte#100] opened 2016-09-09 19:28 UTC
When I render the component using `createValueFromString` and then update the state using `toString`, it types the text backwards. i.e. when I type 'hippo', it renders it backwards like 'oppih' and the cursor if on the right-side of the textarea. Not sure if I'm doing something wrong or if its a bug.
Update: I also noticed that the 'undo' and 'redo' icons don't work and are always disabled when I implement the component this way.

```
import React, {Component, PropTypes} from 'react';
import RichTextEditor from 'react-rte';

class MyStatefulEditor extends Component {
  static propTypes = {
    onChange: PropTypes.func
  };
  state = {
    value: null
  }
onChange = (s) => {
         this.setState({value: s.toString('html')});
};
getValue = () => {
        let nv = this.state.value || '';
        return RichTextEditor.createValueFromString(nv, 'html');
};
  render () {
    return (
      <RichTextEditor
        value={getValue()}
        onChange={this.onChange}
      />
    );
  }
}
```

**Comment by shawnmclean** [comment] 2016-09-14 03:32
Are you by any chance using `redux-form`? I'm using code like yours as a component in a redux form. The words are typed in reverse and my undo button only goes back 1 level, but redo is disabled.

**Comment by cfkenandy** [comment] 2016-09-14 17:10
I’m not using redux-form however, I’m using redux. I get this error when you re-initialize the state onChange i.e. call toString over and over. For some reason this messes up the initial configuration. Their examples say “it would be better to avoid generating a string on each change.”. I’ve been able to get around this problem by not calling toString unless I have to submit the form/commit a change. Not sure if there is a better way of doing it.

**Comment by davidglbr** [comment] 2016-09-15 13:07
@cfkenandy had this problem too, not sure why

**Comment by ForbesLindesay** [comment] 2016-09-15 13:28
This is nothing to do with redux.  The problem is that the `value` you get from `createValueFromString` is the complete sate of the editor.  In addition to the content, this includes things like the current position of the cursor.  When you get that state from a string, it just puts the cursor at the beginning.  When you convert it back to a string, you discard the current position of the cursor.

The best way to do this is only to use `createValueFromString` to get the initial value, and then store the actual value in `this.state`.  You can then use `value.toString('html')` only when you need to save or render the value as HTML.

If you want, you can wrap this behaviour up in a component.  This editor has internal state, but the state is completely contained, so you can use it as if it were a stateless editor.  This is an example of where you should keep the state local, not put it in redux.  An example of what this looks like is:

```js
class HTMLEditor extends Component {
  static propTypes = {
    value: PropTypes.string.isRequired,
    onChange: PropTypes.func.isRequired,
  };

  state = {
    richValue: RichTextEditor.createValueFromString(props.value, 'html'),
    htmlValue: props.value,
  };

  componentWillReceiveProps (newProps) {
    if (newProps.value != this.state.htmlValue) {
      this.setState({
        richValue: RichTextEditor.createValueFromString(newProps.value, 'html'),
        htmlValue: newProps.value,
      });
    }
  }

  onChange = (richValue) => {
    this.setState({richValue, htmlValue: richValue.toString('html')}, () => {
      this.props.onChange(this.state.htmlValue);
    });
  };

  render () {
    return (
      <RichTextEditor
        value={this.state.richValue}
        onChange={this.onChange}
      />
    );
  }
}
```

Note that we are storing the `htmlValue` (a string of HTML) and a `richValue` (the full state of the editor).  When anything gets updated, we update both in the state, and send the htmlValue to any parent components.  Every time we get an updated `htmlValue`, we compare it to the value stored in `this.state.htmlValue`.  If it's changed, we have to re-generate the state from  the `htmlValue`.  If it's the same, we leave the existing `richValue` in place, so as not to loose cursor positions etc.

**Comment by ForbesLindesay** [comment] 2016-09-15 13:31
Just saw that https://github.com/sstur/react-rte/commit/06ed718a463e6b8ddc0fb88fd868727c475a0daf got added, so you could probably use that.

**Comment by cfkenandy** [comment] 2016-09-15 17:08
Thanks @ForbesLindesay, I pretty much did what you said to get it working "use createValueFromString to get the initial value, and then store the actual value in this.state. You can then use value.toString('html') only when you need to save or render the value as HTML."

**Comment by sstur** [comment] 2016-10-17 16:08
@ForbesLindesay: Thank you for the clear and detailed answer! I'll close this issue now since the OP's issue is not a bug. Thanks!

**Closed by sstur** 2016-10-17 16:08 UTC

**Comment by yarnball** [comment] 2016-10-30 09:22
@ForbesLindesay Thanks for the detailed answer. I'm trying to do it the correct way myself.

I'm not having any success. I keep getting the TypeError -  

> TypeError: Cannot read property 'context'

Have I created the element correctly?

```
var Editor =  React.createClass({
    getInitialState: function() {
      return {
      richValue: RichTextEditor.createValueFromString(this.props.photo.title, 'html'),
      htmlValue: props.value,
     };
    },
  componentWillReceiveProps (newProps) {
    if (newProps.value != this.state.htmlValue) {
      this.setState({
        richValue: RichTextEditor.createEmptyValue(this.props.photo.title, 'html'),
        htmlValue: newProps.value,
      });
    }
  },
  onChangeEditor: function(richValue) {
    this.setState({richValue, htmlValue: richValue.toString('html')}, () => {
      this.props.onChange(this.state.htmlValue);
    });
  },
  render: function(){
        return (
            <RichTextEditor
              value={this.state.richValue}
              onChange={this.onChange}
            />

        );
    }
});
```

**Comment by sstur** [comment] 2016-11-01 13:40
You might want to look at this example and see if it helps:
https://github.com/sstur/react-rte/blob/master/src/SimpleRichTextEditor.js
