### ISSUE TITLE
document not defined

### ISSUE THREAD

**Issue by pnmsharma** [sstur/react-rte#86] opened 2016-07-29 12:12 UTC
Hello , I am getting following issue ,please help me out to sort it.

 **node server.js
/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:12631
        var styleElement = document.createElement("style");
                           ReferenceError: document is not defined**
    at createStyleElement (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:12631:28)
    at addStyle (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:12649:30)
    at addStylesToDom (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:12594:84)
    at module.exports (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:12703:16)
    at Object.<anonymous> (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:12534:29)
    at __webpack_require__ (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:38:34)
    at Object.<anonymous> (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:12458:288)
    at __webpack_require__ (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:38:34)
    at Object.module.exports.classes (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:12357:187)
    at __webpack_require__ (/home/poonam-sharma/Documents/reacthello/node_modules/react-rte/dist/react-rte.js:38:34)

**Comment by ZeroCho** [comment] 2016-08-07 05:38
I think it's related to style-loader

**Comment by pnmsharma** [comment] 2016-08-09 14:56
m using node +gulp+react+flux

**Comment by sstur** [comment] 2016-08-21 08:38
Yes, this is related to Webpack and CSS Modules. There are several other similar issues and I have a pending PR that might solve this. For now I will close this as a duplicate of #81.

**Closed by sstur** 2016-08-21 08:38 UTC
