### ISSUE TITLE
Uses style-loader, which doesn't allow for running on the server side.

### ISSUE THREAD

**Issue by Jock924491** [sstur/react-rte#77] opened 2016-07-13 20:32 UTC
Hello,

First off wanted to say this project is incredibly well done I absolutely love it & want to use this in my project. However, my team does a pre-load run on the server side for build, before running in the client. This project uses style-loader, and the creator hasn't made it to support client usage, without local scopes (see https://github.com/webpack/style-loader/issues/109 & PR https://github.com/webpack/style-loader/pull/115) 

....\node_modules\react-rte\dist\react-rte.js:19795
                        return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
                                                   ^

ReferenceError: window is not defined

**Comment by ZeroCho** [comment] 2016-07-14 11:38
#37 #50

**Comment by sstur** [comment] 2016-07-15 03:43
Thanks @Jock924491!

I've been thinking about all the issues caused by using CSS Modules, and I think the right thing is to migrate this project to [JSS](https://github.com/jsstyles/jss). That will play nicely on the client side and server side because it's just plain JS. It should close a handful of issues.

I will try to get this change in over the next week.

Thanks for using react-rte!

**Comment by episodeyang** [comment] 2016-07-28 01:12
Would it make sense to completely remove the styling from the code base, and leave it to the user? Most people would want to style their on their own anyways.

thanks for this module!

**Comment by sstur** [comment] 2016-08-21 09:21
@episodeyang: I don't think that approach is right for this project because I want this to work out of the box for people by having sensible defaults (similar to dropping CKEditor into a jQuery project). I definitely want to have a way for savvy developers to override our styles and defaults and I would even consider supporting an option to disable all styling but I don't want to remove styles altogether.

**Comment by sstur** [comment] 2016-08-21 09:21
I am closing this in favor of #93.

**Closed by sstur** 2016-08-21 09:21 UTC
