### ISSUE TITLE
Uncaught Invariant Violation: Unknown node in selection range.

### ISSUE THREAD

**Issue by ljovanovic** [sstur/react-rte#85] opened 2016-07-23 11:41 UTC
If you enter text in the editor, and then right-click on a toolbar button the following exception is raised:

Uncaught Invariant Violation: Unknown node in selection range.

This can be reproduced in the demo.

**Comment by ZeroCho** [comment] 2016-07-23 17:28
I can't reproduce it. Which browser do you use?

**Comment by ljovanovic** [comment] 2016-07-23 19:04
Version 51.0.2704.103 (64-bit)

http://g.recordit.co/75THYmOlF6.gif

**Comment by jtraub** [comment] 2016-08-01 12:17
@ljovanovic does the issue persist if you do this in the incognito mode (i.e. without extensions loaded)?

**Comment by Slapbox** [comment] 2016-08-19 21:30
I'm running React-RTE in a Chrome Extension and I'm getting the same behavior. I haven't 100% pinned it down, but it seems to be when I save the content state to HTML and then load it back, on clicking to focus it gives me that.

**Comment by sstur** [comment] 2016-08-21 08:41
I do believe this is related to an extension mutating the DOM within our editor. If all extensions are being well-behaved and not modifying the DOM, then this should probably be opened in https://github.com/facebook/draft-js. For now I will close this issue.

**Closed by sstur** 2016-08-21 08:41 UTC

**Comment by Slapbox** [comment] 2016-08-23 13:30
I'm not 100% sure what I'm doing wrong, but it does seem that this error is my fault. If it turns out not to be the case I'll update here.
