### ISSUE TITLE
Option to open links in new tab

### ISSUE THREAD

**Issue by tiberiumaxim** [sstur/react-rte#170] opened 2017-01-26 08:52 UTC
This is a feature request.
I'm proposing an option such as `openExternalLinksInNewTabs (Bool)`
Once a link is created, a check for whether the link is internal or external is made and for external links the attribute `target="_blank"` is added in the resulting html.

**Comment by alexdiktampanidis** [comment] 2017-09-02 21:37
Very nice plugin but this feature is a must.

Here is a little trick i added in one of my projects:
If you want **all** your links to open in new tab change the value you send from:
`value.toString('html')`
to:
`value.toString('html').replace(/<a /g, '<a target="_blank" ')`

The good thing is that react-rte parses html special characters, so, you don't have to worry about conflicts between simple text and real anchor tags.

**Comment by bherila** [comment] 2017-09-05 14:31
I think this is a duplicate of https://github.com/sstur/react-rte/issues/228

**Closed by bherila** 2017-09-05 14:31 UTC
Labels: duplicate

**Comment by sstur** [comment] 2017-09-07 00:59
To be clear, is this on the HTML output? If so we should open this issue at [draft-js-export-html](https://github.com/sstur/draft-js-utils)
